---
title: "Publications"
css: style2.css
---
<link rel="stylesheet" href="academicons/css/academicons.min.css"/>


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-99094202-1', 'auto');
  ga('send', 'pageview');

</script>

<br>
<br>

#### Selected Publications on Wearables/Digital Measurements


<!-- 1. Kuo, PL., __Di, J.__, Ferrucci L., and Lin, FR.. Analysis of hearing loss and physical activity among US adults, 60 - 69 years old. _JAMA Network Open_. 2021. -->

1. Mahadevan, N., Christakis, Y., __Di, J.__, Bruno, J., Zhang Y., Dorsey, ER., Pigeon, WR., Beck, LA., Thomas, K., Liu, Y., Wicker, M., Brooks, C., Kabiri, NS., Bhangu, J., Northcott, C., and Patel, S.. [Development of digital measures for nighttime scratch and sleep using wrist-worn wearable devices](https://www.nature.com/articles/s41746-021-00402-x). _Nature npj Digital Medicine_. 2021. 
Behind the paper blog post: [Wearable sensors can tell you more than just step count: measuring nighttime scratching and sleep](https://go.nature.com/3e2M4TH).
2. Wanigatunga, A., __Di, J.__, Zipunnikov, V., Urbanek, J., Kuo, P., Simonsick, EM., Ferrucci, L., and Schrack, J.. [Association of total daily physical activity and fragmented physical activity with mortality in older adults](https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2752084). _JAMA Network Open_. 2019.
3. __Di, J.__, Spira, A., Bai, J., Urbanek, J., Leroux, A., Wu, M., Resnik, S., Simonsick, E., Ferrucci, L., Schrack, J., and Zipunnikov, V.. [Joint and individual representation of domains of physical activity, sleep, and circadian rhythmicity](https://link.springer.com/article/10.1007/s12561-019-09236-4). _Statistics in Biosciences_. 2019. 
4. Johns, J., __Di, J.__, Merikangas, K., Cui, L., Swendsen, J., and Zipunnikov, V.. [Fragmentation as a novel measure of stability in normalized trajectories of mood and attention measured by ecological momentary assessment](https://psycnet.apa.org/doiLanding?doi=10.1037%2Fpas0000661). _Psychological Assessment_. 2019.
5. Leroux, A., __Di, J.__, Smirnova, E., Mcguffey, E., Cao, Q., Bayatmokhtari, E., Tabacu, L., Zipunnikov, V., Urbanek, J., Crainiceanu, C.. [Organizing and analyzing the activity data in NHANES](https://link.springer.com/article/10.1007/s12561-018-09229-9). _Statistics in Biosciences_. 2019.
6. Schrack, J., Kuo, P., Wanigatunag, A., __Di, J.__, Simonsick, EM., Spira, A., Ferrucci, L., and Zipunnikov, V.. [Active-to-sedentary behavior transition, fatigability, and physical functioning in older adults](https://academic.oup.com/biomedgerontology/advance-article/doi/10.1093/gerona/gly243/5144068). _The Journal of Gerontology: Series A_. 2019. 
7. Urbanek, J., Spira, A., __Di, J.__, Leroux, A., Crainiceanu, C., and Zipunnikov, V.. [Epidemiology of objectively measured bedtime and chronotype in US adolescents and adults: NHANES 2003 - 2006](http://www.tandfonline.com/doi/full/10.1080/07420528.2017.1411359). _Chronobiology International_. 2018.
8. Varma, V., Dey D., Leroux A., __Di, J.__, Urbanek, J., Xiao, L., and Zipunnikov, V.. [Total volume of physical activity: TAC, TLAC, or TAC($\lambda$)](http://www.sciencedirect.com/science/article/pii/S0091743517303997). _Preventive Medicine_. 2018.
9. __Di, J.__, Leroux, A., Urbanek, R., Varadhan, J., Spira, A., Schrack, J., and Zipunnikov, V.. Patterns of sedentary and active time accumulation are associated with mortality in US adults: The NHANES study. [bioRxiv: 182337](http://www.biorxiv.org/content/early/2017/08/31/182337). 
10. Varma, V., Dey D., Leroux A., __Di, J.__, Urbanek, J., Xiao, L., and Zipunnikov, V.. [Re-evaluating the effect of age on physical activity over the lifespan](http://www.sciencedirect.com/science/article/pii/S0091743517301949). _Preventive Medicine_. 2017..

<br>

A full list of my publications can be found on my [Google Scholar page](https://scholar.google.com/citations?user=9YSnIL4AAAAJ&hl=en).
<br>
<br>


#### Softwares

1. __cdHOTS__. (R package). Construct and decompose higher order tensorian statistics.[[Github](https://github.com/junruidi/cdHOTS)]
2. __actigraphy-profiles__. (R Shiny App). A visualization tool for displaying minute-level actigraphy profiles (More features to be online). [[Github](https://github.com/junruidi/actigraphy-profiles)]
3. __ActFrag__. (R package). Activity fragmentation metrics extraced from minute level actigraphy data. [[Github](https://github.com/junruidi/ActFrag)] [[CRAN](https://cran.r-project.org/web/packages/ActFrag/index.html)]
[[Osler](https://oslerinhealth.org/package/ActFrag)]
4. __ActCR__. (R package). Extract circadian rhythms metrics from actigraphy data. [[Github](https://github.com/junruidi/ActCR)][[CRAN](https://cran.r-project.org/web/packages/ActCR/index.html)]


