---
title: "Research"
css: style2.css
---

#

#

I develop and implement statstistical methodology to solve for scientific problems under the advisement of [Dr. Vadim Zipunnikov](http://www.biostat.jhsph.edu/~vzipunni/). My major research interest is related to [Wearable Computing Device](http://www.smart-stats.org/content/wearable-computing-accelerometers-heart-monitors-actigraphs) ([accelerometers](https://en.wikipedia.org/wiki/Accelerometer), [actigraphs](https://en.wikipedia.org/wiki/Actigraphy), etc.). Recently, these devices have gained their popularity in both academia and industry; however, accurately analyzing data generated by them remains a big scientific chanllange. Understanding this type of data, their distribution within person and in the population can help understand the association between these new measurements and human health. I am mostly interested in extracting information (both with parametric and nonparametric statistical approaches)  to summarize noisy and high dimensional activity profiles.

__Scientific Interests__: wearable devices, physical activity assessment, mHealth, sleep, circadian rhythm, gerontological epidemiology.

__Statistical Methods__: feature extraction from accelerometers, functional data analysis, matrix decomposition and matrix-variate analysis, multilevel data analysis.

###Selected Research Projects
- __Modeling Activity Transition Matrix using Bivariate Exponential Distribution__:
Modeled subject level activity transiton matrices (i.e. from sedentary to active, and from active to sedentary) using bivariate exponential distirbution (Marshall Okins) and Hiden Mokov Models. 

- __Novel Statistical Framework to Quantify Activity Fragmentation__: Developed a statistical framework to quantify activity fragmentation by analyzing emperical distribution functions of sedentary and acitve time  using both parametric and non parametric metrics with application to predicting mortality usiang NHANES 2003 - 2006

- __Processed the NHANES 2003 - 2006 Accelerometery Data__: Proposed a data storage and annotation protocol for minute level activity count data. Processed high dimensonal and messy NHANES 2003 - 2006 accelerometery data to the proposed user friendly wide . Provided ready-to-use R functions and tutorial for future researchers to conduct statistlca analysis on NHANES accelerometery data. 






