---
title: "Teaching"
css: style2.css
---
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-99094202-1', 'auto');
  ga('send', 'pageview');

</script>
#


#
I have served as a teaching assistant on a wide variety of courses in the department of biostatistics; the following is a chronological list:

<center>
Term  | Course Number| Title  | Notes
---------| -------------| ----------------------- | -----
Spring 2019   |  PH.140.623   |  Statistical Methods in Public Health III | __Lab Instructor__$^\dagger$
Fall 2018   |  PH.140.621   |  Statistical Methods in Public Health I   | __Lab Instructor__$^\dagger$
Spring 2018   |  PH.140.623   |  Statistical Methods in Public Health III | __Lab Instructor__$^\dagger$
Fall 2017   |  PH.140.621   |  Statistical Methods in Public Health I   | __Lab Instructor__$^\dagger$
Spring 2017   |   PH.140.623-4   |   Statistical Methods in Public Health III-IV   |
Fall 2016   |   PH.140.621-2   |   Statistical Methods in Public Health I-II   |
Spring 2016   |   PH 140.753-4   |   Advanced Methods in Biostatistics III-IV  | 
Fall 2015   |   PH 140.751-2   |   Advanced Methods in Biostatistics I-II   | 
Spring 2014   |   BIST 514  |   Linear Modeling & Multivariate Analysis   | Georgetown
</center>

$\dagger$: Responsibilities involve holding 2 - 3 lab lectures per week, beta-testing quizzes and exams, participating in TA meetings and providing oversight for the other TAs

